#!/bin/sh

# Navigate to the base directory
cd "${0%/*}/.."

c2str() {
    awk -v enum="$1" -v label="$2" '
    	BEGIN {
        	prefix = "MPIX_" toupper(label) "_"

        	print ""
        	print "const struct mpix_str mpix_str_" label "[] = {"
        }

        (!enum && sub("#define " prefix, "")) || (enum && sub("\t" prefix, "")) {
            gsub(",", "")
            printf "\t{%-16s %s},\n", "\"" $1 "\",", prefix $1
        }

        END {
            print "\t{},"
            print "};"
        }

    ' include/mpix/*.h
}

exec >src/str.c

echo "/* SPDX-License-Identifier: Apache-2.0 */"
echo "/* Generated by scripts/genstr.sh */"
echo ""
echo "#include <mpix/str.h>"
echo "#include <mpix/image.h>"

c2str 0 fmt
c2str 1 kernel
c2str 1 resize
c2str 1 correction
c2str 1 jpeg_quality
