/* SPDX-License-Identifier: Apache-2.0 */
/* Generated by scripts/genstr.sh */

#include <mpix/formats.h>
#include <mpix/genlist.h>
#include <mpix/types.h>
#include <mpix/utils.h>

const struct mpix_str mpix_str_fmt[] = {
#define MPIX_STR_FMT(X, x) \
	{#X, MPIX_FMT_##X},
MPIX_FOR_EACH_FMT(MPIX_STR_FMT)
	{},
};

const char * const mpix_str_op[] = {
#define MPIX_STR_OP(X, x) \
	[MPIX_OP_##X] = #X,
MPIX_FOR_EACH_OP(MPIX_STR_OP)
};

const char * const mpix_str_kernel[] = {
#define MPIX_STR_KERNEL(X, x) \
	[MPIX_KERNEL_##X] = #X,
MPIX_FOR_EACH_KERNEL(MPIX_STR_KERNEL)
};

const char * const mpix_str_jpeg[] = {
#define MPIX_STR_JPEG(X, x) \
	[MPIX_JPEG_##X] = #X,
MPIX_FOR_EACH_JPEG(MPIX_STR_JPEG)
};

const char * const mpix_str_cid[] = {
#define MPIX_STR_CID(X, x) \
	[MPIX_CID_##X] = #X,
MPIX_FOR_EACH_CID(MPIX_STR_CID)
};
