/* SPDX-License-Identifier: Apache-2.0 */
/* Generated by scripts/genstr.sh */

#include <mpix/str.h>
#include <mpix/image.h>

const struct mpix_str mpix_str_fmt[] = {
	{"RGB332",        MPIX_FMT_RGB332},
	{"RGB565",        MPIX_FMT_RGB565},
	{"RGB565X",       MPIX_FMT_RGB565X},
	{"RGB24",         MPIX_FMT_RGB24},
	{"XRGB32",        MPIX_FMT_XRGB32},
	{"YUV12",         MPIX_FMT_YUV12},
	{"YUV24",         MPIX_FMT_YUV24},
	{"YUYV",          MPIX_FMT_YUYV},
	{"GREY",          MPIX_FMT_GREY},
	{"SBGGR8",        MPIX_FMT_SBGGR8},
	{"BGGR8",         MPIX_FMT_BGGR8},
	{"SGBRG8",        MPIX_FMT_SGBRG8},
	{"SGRBG8",        MPIX_FMT_SGRBG8},
	{"SRGGB8",        MPIX_FMT_SRGGB8},
	{"PALETTE1",      MPIX_FMT_PALETTE1},
	{"PALETTE2",      MPIX_FMT_PALETTE2},
	{"PALETTE3",      MPIX_FMT_PALETTE3},
	{"PALETTE4",      MPIX_FMT_PALETTE4},
	{"PALETTE5",      MPIX_FMT_PALETTE5},
	{"PALETTE6",      MPIX_FMT_PALETTE6},
	{"PALETTE7",      MPIX_FMT_PALETTE7},
	{"PALETTE8",      MPIX_FMT_PALETTE8},
	{"JPEG",          MPIX_FMT_JPEG},
	{"QOI",           MPIX_FMT_QOI},
	{},
};

const struct mpix_str mpix_str_kernel[] = {
	{"IDENTITY",      MPIX_KERNEL_IDENTITY},
	{"EDGE_DETECT",   MPIX_KERNEL_EDGE_DETECT},
	{"GAUSSIAN_BLUR", MPIX_KERNEL_GAUSSIAN_BLUR},
	{"SHARPEN",       MPIX_KERNEL_SHARPEN},
	{"DENOISE",       MPIX_KERNEL_DENOISE},
	{},
};

const struct mpix_str mpix_str_resize[] = {
	{"SUBSAMPLING",   MPIX_RESIZE_SUBSAMPLING},
	{"BINNING",       MPIX_RESIZE_BINNING},
	{},
};

const struct mpix_str mpix_str_correction[] = {
	{"BLACK_LEVEL",   MPIX_CORRECTION_BLACK_LEVEL},
	{"WHITE_BALANCE", MPIX_CORRECTION_WHITE_BALANCE},
	{"GAMMA",         MPIX_CORRECTION_GAMMA},
	{},
};

const struct mpix_str mpix_str_jpeg_quality[] = {
	{"DEFAULT",       MPIX_JPEG_QUALITY_DEFAULT},
	{},
};
